name: MLOps Pipeline

on:
  schedule:
    - cron: '*/15 * * * *' # Every 15 minutes
  workflow_dispatch: # Allow manual trigger

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to commit changes

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Training Flow
      run: python run_training_flow.py
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}

    - name: Run Monitoring Flow
      run: python run_monitoring.py
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}

    - name: Run Inference Flow (Existing Customers)
      run: python run_existing_customer_inference.py
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}

    - name: Commit and Push Changes
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        # Add specific files we expect to change
        git add models/ reports/ data/processed/
        # Commit only if there are changes
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update: Model and Reports [skip ci]" && git push)
